import { Package } from '@/types';

export const defaultPackages: Package[] = [
  // Viettel
  {
    id: 'viettel-4g-30gb',
    name: 'Viettel 4G 170GB',
    carrier: 'Viettel',
    price: 150000,
    originalPrice: 200000,
    data: '170GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '100 phút',
    sms: '100 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Không giới hạn tốc độ'],
    badge: 'Hot',
    description: 'Gói cước 4G tốc độ cao với 170GB data, phù hợp cho người dùng thường xuyên. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.'
  },
  {
    id: 'viettel-5g-unlimited',
    name: 'Viettel 5G Unlimited',
    carrier: 'Viettel',
    price: 300000,
    data: 'Unlimited',
    speed: '5G',
    validity: '30 ngày',
    callMinutes: 'Unlimited',
    sms: 'Unlimited',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Data không giới hạn', 'Phát wifi', 'Gọi nội mạng miễn phí'],
    badge: 'BEST VALUE',
  },
  {
    id: 'viettel-4g-50gb',
    name: 'Viettel 4G 190GB',
    carrier: 'Viettel',
    price: 200000,
    data: '190GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '200 phút',
    sms: '200 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Data lớn'],
  },
  
  // Vinaphone
  {
    id: 'vinaphone-4g-20gb',
    name: 'Vinaphone 4G 160GB',
    carrier: 'Vinaphone',
    price: 120000,
    data: '90GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '50 phút',
    sms: '50 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
    badge: 'Hot',
  },
  {
    id: 'vinaphone-4g-40gb',
    name: 'Vinaphone 4G 180GB',
    carrier: 'Vinaphone',
    price: 180000,
    data: '180GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '150 phút',
    sms: '150 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Data lớn'],
  },
  
  // MobiFone
  {
    id: 'mobifone-4g-25gb',
    name: 'MobiFone 4G 165GB',
    carrier: 'MobiFone',
    price: 130000,
    data: '165GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '80 phút',
    sms: '80 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  {
    id: 'mobifone-4g-35gb',
    name: 'MobiFone 4G 175GB',
    carrier: 'MobiFone',
    price: 170000,
    data: '175GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '120 phút',
    sms: '120 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // Vietnamobile
  {
    id: 'vietnamobile-4g-15gb',
    name: 'Vietnamobile 4G 115GB',
    carrier: 'Vietnamobile',
    price: 100000,
    data: '115GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '30 phút',
    sms: '30 SMS',
    hotspot: false,
    features: ['4G tốc độ cao'],
  },
  {
    id: 'vietnamobile-4g-25gb',
    name: 'Vietnamobile 4G 165GB',
    carrier: 'Vietnamobile',
    price: 140000,
    data: '165GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '60 phút',
    sms: '60 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // Gmobile
  {
    id: 'gmobile-4g-10gb',
    name: 'Gmobile 4G 110GB',
    carrier: 'Gmobile',
    price: 80000,
    data: '110GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '20 phút',
    sms: '20 SMS',
    hotspot: false,
    features: ['4G tốc độ cao'],
  },
  {
    id: 'gmobile-4g-20gb',
    name: 'Gmobile 4G 160GB',
    carrier: 'Gmobile',
    price: 120000,
    data: '160GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '40 phút',
    sms: '40 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // iTel
  {
    id: 'itel-4g-12gb',
    name: 'iTel 4G 112GB',
    carrier: 'iTel',
    price: 90000,
    data: '112GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '25 phút',
    sms: '25 SMS',
    hotspot: false,
    features: ['4G tốc độ cao'],
  },
  {
    id: 'itel-4g-22gb',
    name: 'iTel 4G 162GB',
    carrier: 'iTel',
    price: 130000,
    data: '162GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '50 phút',
    sms: '50 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // Wintel
  {
    id: 'wintel-4g-18gb',
    name: 'Wintel 4G 158GB',
    carrier: 'Wintel',
    price: 110000,
    data: '158GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '40 phút',
    sms: '40 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  {
    id: 'wintel-4g-28gb',
    name: 'Wintel 4G 168GB',
    carrier: 'Wintel',
    price: 150000,
    data: '168GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '70 phút',
    sms: '70 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // VNSKY
  {
    id: 'vnsky-4g-14gb',
    name: 'VNSKY 4G 114GB',
    carrier: 'VNSKY',
    price: 95000,
    data: '114GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '30 phút',
    sms: '30 SMS',
    hotspot: false,
    features: ['4G tốc độ cao'],
  },
  {
    id: 'vnsky-4g-24gb',
    name: 'VNSKY 4G 164GB',
    carrier: 'VNSKY',
    price: 135000,
    data: '164GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '55 phút',
    sms: '55 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // Local
  {
    id: 'local-4g-8gb',
    name: 'Local 4G 108GB',
    carrier: 'Local',
    price: 70000,
    data: '108GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '15 phút',
    sms: '15 SMS',
    hotspot: false,
    features: ['4G tốc độ cao'],
  },
  {
    id: 'local-4g-16gb',
    name: 'Local 4G 156GB',
    carrier: 'Local',
    price: 105000,
    data: '156GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '35 phút',
    sms: '35 SMS',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi'],
  },
  
  // Thêm gói 5G cho các nhà mạng lớn
  {
    id: 'viettel-5g-50gb',
    name: 'Viettel 5G 250GB',
    carrier: 'Viettel',
    price: 250000,
    data: '250GB',
    speed: '5G',
    validity: '30 ngày',
    callMinutes: 'Unlimited',
    sms: 'Unlimited',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Data lớn', 'Phát wifi', 'Gọi nội mạng miễn phí'],
    badge: 'NEW',
  },
  {
    id: 'vinaphone-5g-40gb',
    name: 'Vinaphone 5G 240GB',
    carrier: 'Vinaphone',
    price: 220000,
    data: '240GB',
    speed: '5G',
    validity: '30 ngày',
    callMinutes: '200 phút',
    sms: '200 SMS',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Data lớn', 'Phát wifi'],
    badge: 'NEW',
  },
  {
    id: 'mobifone-5g-35gb',
    name: 'MobiFone 5G 235GB',
    carrier: 'MobiFone',
    price: 210000,
    data: '235GB',
    speed: '5G',
    validity: '30 ngày',
    callMinutes: '150 phút',
    sms: '150 SMS',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Data lớn', 'Phát wifi'],
    badge: 'NEW',
  },
  
  // Thêm gói giá rẻ
  {
    id: 'viettel-4g-15gb',
    name: 'Viettel 4G 115GB',
    carrier: 'Viettel',
    price: 100000,
    data: '85GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '50 phút',
    sms: '50 SMS',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Giá rẻ'],
  },
  {
    id: 'vinaphone-4g-10gb',
    name: 'Vinaphone 4G 180GB',
    carrier: 'Vinaphone',
    price: 90000,
    data: '110GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '30 phút',
    sms: '30 SMS',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Giá rẻ'],
  },
  {
    id: 'mobifone-4g-15gb',
    name: 'MobiFone 4G 115GB',
    carrier: 'MobiFone',
    price: 100000,
    data: '115GB',
    speed: '4G',
    validity: '30 ngày',
    callMinutes: '40 phút',
    sms: '40 SMS',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Giá rẻ'],
  },
  
  // ========== GÓI NĂM (YEARLY PACKAGES) ==========
  
  // Viettel Gói Năm
  {
    id: 'viettel-4g-30gb-year',
    name: 'Viettel 4G Unlimited - Gói Năm',
    carrier: 'Viettel',
    price: 1500000, // ~12 tháng x 150k = 1.8M, giảm 17%
    originalPrice: 1800000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '100 phút/tháng',
    sms: '100 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng', 'Không giới hạn tốc độ'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G tốc độ cao với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng thường xuyên, cam kết sử dụng lâu dài. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'viettel-4g-50gb-year',
    name: 'Viettel 4G Unlimited - Gói Năm',
    carrier: 'Viettel',
    price: 2000000, // ~12 tháng x 200k = 2.4M, giảm 17%
    originalPrice: 2400000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '200 phút/tháng',
    sms: '200 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data lớn hàng tháng', 'Gọi nội mạng miễn phí'],
    badge: 'BEST VALUE',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng cần nhiều data, làm việc và giải trí. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'viettel-5g-unlimited-year',
    name: 'Viettel 5G Unlimited - Gói Năm',
    carrier: 'Viettel',
    price: 3000000, // ~12 tháng x 300k = 3.6M, giảm 17%
    originalPrice: 3600000,
    data: 'Unlimited/tháng',
    speed: '5G',
    validity: '365 ngày',
    callMinutes: 'Unlimited',
    sms: 'Unlimited',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Data không giới hạn', 'Phát wifi', 'Tiết kiệm 17%', 'Gọi nội mạng miễn phí', 'SMS không giới hạn'],
    badge: 'PREMIUM',
    description: 'Gói cước 5G không giới hạn data, gọi và SMS. Tiết kiệm 17% so với mua hàng tháng. Phù hợp cho doanh nghiệp và người dùng cao cấp. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // Vinaphone Gói Năm
  {
    id: 'vinaphone-4g-20gb-year',
    name: 'Vinaphone 4G Unlimited - Gói Năm',
    carrier: 'Vinaphone',
    price: 1200000, // ~12 tháng x 120k = 1.44M, giảm 17%
    originalPrice: 1440000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '50 phút/tháng',
    sms: '50 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'vinaphone-4g-40gb-year',
    name: 'Vinaphone 4G Unlimited - Gói Năm',
    carrier: 'Vinaphone',
    price: 1800000, // ~12 tháng x 180k = 2.16M, giảm 17%
    originalPrice: 2160000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '150 phút/tháng',
    sms: '150 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data lớn hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng cần nhiều data. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'vinaphone-5g-40gb-year',
    name: 'Vinaphone 5G Unlimited - Gói Năm',
    carrier: 'Vinaphone',
    price: 2200000, // ~12 tháng x 220k = 2.64M, giảm 17%
    originalPrice: 2640000,
    data: 'Unlimited - Tốc độ cao',
    speed: '5G',
    validity: '365 ngày',
    callMinutes: '200 phút/tháng',
    sms: '200 SMS/tháng',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data lớn hàng tháng'],
    badge: 'NEW',
    description: 'Gói cước 5G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Trải nghiệm tốc độ 5G siêu nhanh. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // MobiFone Gói Năm
  {
    id: 'mobifone-4g-25gb-year',
    name: 'MobiFone 4G Unlimited - Gói Năm',
    carrier: 'MobiFone',
    price: 1300000, // ~12 tháng x 130k = 1.56M, giảm 17%
    originalPrice: 1560000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '80 phút/tháng',
    sms: '80 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'mobifone-4g-35gb-year',
    name: 'MobiFone 4G Unlimited - Gói Năm',
    carrier: 'MobiFone',
    price: 1700000, // ~12 tháng x 170k = 2.04M, giảm 17%
    originalPrice: 2040000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '120 phút/tháng',
    sms: '120 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data lớn hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng cần nhiều data. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'mobifone-5g-35gb-year',
    name: 'MobiFone 5G Unlimited - Gói Năm',
    carrier: 'MobiFone',
    price: 2100000, // ~12 tháng x 210k = 2.52M, giảm 17%
    originalPrice: 2520000,
    data: 'Unlimited - Tốc độ cao',
    speed: '5G',
    validity: '365 ngày',
    callMinutes: '150 phút/tháng',
    sms: '150 SMS/tháng',
    hotspot: true,
    features: ['5G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data lớn hàng tháng'],
    badge: 'NEW',
    description: 'Gói cước 5G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Trải nghiệm tốc độ 5G siêu nhanh. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // Vietnamobile Gói Năm
  {
    id: 'vietnamobile-4g-15gb-year',
    name: 'Vietnamobile 4G Unlimited - Gói Năm',
    carrier: 'Vietnamobile',
    price: 1000000, // ~12 tháng x 100k = 1.2M, giảm 17%
    originalPrice: 1200000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '30 phút/tháng',
    sms: '30 SMS/tháng',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng tiết kiệm. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'vietnamobile-4g-25gb-year',
    name: 'Vietnamobile 4G Unlimited - Gói Năm',
    carrier: 'Vietnamobile',
    price: 1400000, // ~12 tháng x 140k = 1.68M, giảm 17%
    originalPrice: 1680000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '60 phút/tháng',
    sms: '60 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // Gmobile Gói Năm
  {
    id: 'gmobile-4g-10gb-year',
    name: 'Gmobile 4G Unlimited - Gói Năm',
    carrier: 'Gmobile',
    price: 800000, // ~12 tháng x 80k = 960k, giảm 17%
    originalPrice: 960000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '20 phút/tháng',
    sms: '20 SMS/tháng',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng tiết kiệm. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'gmobile-4g-20gb-year',
    name: 'Gmobile 4G Unlimited - Gói Năm',
    carrier: 'Gmobile',
    price: 1200000, // ~12 tháng x 120k = 1.44M, giảm 17%
    originalPrice: 1440000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '40 phút/tháng',
    sms: '40 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // iTel Gói Năm
  {
    id: 'itel-4g-12gb-year',
    name: 'iTel 4G Unlimited - Gói Năm',
    carrier: 'iTel',
    price: 900000, // ~12 tháng x 90k = 1.08M, giảm 17%
    originalPrice: 1080000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '25 phút/tháng',
    sms: '25 SMS/tháng',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng tiết kiệm. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'itel-4g-22gb-year',
    name: 'iTel 4G Unlimited - Gói Năm',
    carrier: 'iTel',
    price: 1300000, // ~12 tháng x 130k = 1.56M, giảm 17%
    originalPrice: 1560000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '50 phút/tháng',
    sms: '50 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với 1022GB data mỗi tháng, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải.',
  },
  
  // Wintel Gói Năm
  {
    id: 'wintel-4g-18gb-year',
    name: 'Wintel 4G Unlimited - Gói Năm',
    carrier: 'Wintel',
    price: 1100000, // ~12 tháng x 110k = 1.32M, giảm 17%
    originalPrice: 1320000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '40 phút/tháng',
    sms: '40 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'wintel-4g-28gb-year',
    name: 'Wintel 4G Unlimited - Gói Năm',
    carrier: 'Wintel',
    price: 1500000, // ~12 tháng x 150k = 1.8M, giảm 17%
    originalPrice: 1800000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '70 phút/tháng',
    sms: '70 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng cần nhiều data. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // VNSKY Gói Năm
  {
    id: 'vnsky-4g-14gb-year',
    name: 'VNSKY 4G Unlimited - Gói Năm',
    carrier: 'VNSKY',
    price: 950000, // ~12 tháng x 95k = 1.14M, giảm 17%
    originalPrice: 1140000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '30 phút/tháng',
    sms: '30 SMS/tháng',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng tiết kiệm. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'vnsky-4g-24gb-year',
    name: 'VNSKY 4G Unlimited - Gói Năm',
    carrier: 'VNSKY',
    price: 1350000, // ~12 tháng x 135k = 1.62M, giảm 17%
    originalPrice: 1620000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '55 phút/tháng',
    sms: '55 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  
  // Local Gói Năm
  {
    id: 'local-4g-8gb-year',
    name: 'Local 4G Unlimited - Gói Năm',
    carrier: 'Local',
    price: 700000, // ~12 tháng x 70k = 840k, giảm 17%
    originalPrice: 840000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '15 phút/tháng',
    sms: '15 SMS/tháng',
    hotspot: false,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'TIẾT KIỆM',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng tiết kiệm. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
  {
    id: 'local-4g-16gb-year',
    name: 'Local 4G Unlimited - Gói Năm',
    carrier: 'Local',
    price: 1050000, // ~12 tháng x 105k = 1.26M, giảm 17%
    originalPrice: 1260000,
    data: 'Unlimited - Tốc độ cao',
    speed: '4G',
    validity: '365 ngày',
    callMinutes: '35 phút/tháng',
    sms: '35 SMS/tháng',
    hotspot: true,
    features: ['4G tốc độ cao', 'Vùng bắt sóng rộng khắp toàn quốc', 'Phát wifi', 'Tiết kiệm 17%', 'Data hàng tháng'],
    badge: 'HOT',
    description: 'Gói cước 4G với Unlimited data, tiết kiệm 17% so với mua hàng tháng. Phù hợp cho người dùng vừa phải. 4G/5G sẽ hiển thị trên điện thoại tùy theo vùng bắt sóng.',
  },
];

